# .github/workflows/upstream.yml
name: Upstream PR
on:
  schedule:
  - cron: "0 6 * * *" 
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - uses: fopina/upstream-to-pr@v1
        with:
          token: ${{ secrets.PAT }}
          upstream-repository: https://github.com/TabooLib/adyeshach
          upstream-branch: "2.0"